1. WELCOME
2. DO U WANT TO START 
3. ENTER YOUR PASSWORD
    IF PASSWORD = "ADMIN123"
    SHOW MENU
    ACCESS DENIED
4. MENU : 
    ADD CUSTOMERS
    OPEN ACCOUNT
    DEPOSIT AMOUNT
    WITHDRAW AMOUNT
    SEARCH CUSTOMER USING ACC NUMBER/NAME
    VIEW TRANSACTION
    ACTIVATE/DEACTIVATE ACCOUNT
    APPLY FOR LOAN
    DELETE YOUR ACCOUNT